### PR TITLE
Remove redundant flag that breaks MacOS

### PR DESCRIPTION
**Pull request by jeroen**
Currently R users on MacOS cannot use `gmm` without installing custom fortran compilers:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/runner/work/_temp/Library/gmm/libs/gmm.so':
  dlopen(/Users/runner/work/_temp/Library/gmm/libs/gmm.so, 6): Library not loaded: /opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0/libgomp.1.dylib
  Referenced from: /Users/runner/work/_temp/Library/gmm/libs/gmm.so
  Reason: image not found
```

For example here: https://github.com/r-universe/remlapmot/actions/runs/5105299651/jobs/9270554064

However afaict, the dependency on `gomp` is not needed at all, because you are not using OMP in your code. I think you can just remove it and avoid all trouble.

### CODE REVIEW

**Comment by pchausse** [comment]
Thanks for providing a solution to this problem.

**Comment by jeroen** [comment]
You're welcome. Would you mind submitting an update to CRAN, such that MacOS users can use the CRAN version of gmm and packages that depend on gmm?

**Comment by pchausse** [comment]
Just did.

**Comment by remlapmot** [comment]
Thank you very much @pchausse and @jeroen . It will be great to have this fixed.

Additionally, @pchausse I believe that the same fix is probably needed in your companion package [**momentfit**](https://cran.r-project.org/package=momentfit) as that has the same flag currently set in its `src/Makevars`. I couldn't find the repo for that, so leaving this comment here.

**Comment by pchausse** [comment]
Correct. I also fixed it in momenfit and submitted the new version to CRAN (already on it).

**Comment by remlapmot** [comment]
Brilliant, thanks very much again.

**Pull request merged**
